from tsv_modules import *

# Download data files from here: https://developer.imdb.com/non-commercial-datasets/
# Extract and move .tsv files into the same folder as this file.
# Insert .tsv file names below.
files = TsvFile(title_file='title_data', ratings_file='ratings_data')

# Delete old files generated by this script.
tsv_file_delete()

# Removes unnecessary tvEpisode, isAdult and endYear data from tsv.
files.tsv_title_cleanup()

# Merges rating data .tsv and title data .tsv based on matching 'tconst' title identifiers.
# Deletes file generated by tsv_title_cleanup as it is no longer used.
files.tsv_merge()

# Splits file generated by tsv_merge into files based on content type. (movie, tv show, etc.)
# Deletes file generated by tsv_merge as it is no longer used.
titletype_split()
