name: (Merge or push to Main) E2E test

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-24.04

    timeout-minutes: 10
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build and start Randwatch-server and Randwatch-db
        working-directory: dev
        run: docker compose -f compose.yaml up -d --build

      - name: Cache Playwright image
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ './dev/tests/e2e/Dockerfile' }}

      - name: Playwright build and run docker image
        working-directory: dev/tests/e2e
        run: |
          docker build -t playwright-testing .
          docker run -it --name=playwright-testing -d --ipc=host --add-host host.docker.internal:host-gateway playwright-testing

      - name: Playwright run E2E test
        run: docker exec playwright-testing npx playwright test

      - name: If Playwright failed upload test report
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
